### ISSUE TITLE
Approach

### ISSUE THREAD

**Issue by vr00n** [davidfoerster/schema-matching#1]
Hey David - We are looking into using this and wondering if you can give us a small blurb as how how you approached this solution. Does the implementation use a specific form of string similarity to assess schema matches?

Thanks!

**Comment by davidfoerster** [comment]
You're welcome to use this project of mine and, yes, it can base its assessment on string similarity (based on the Levenshtein distance) among other things. Do you have an issue to report with this project or code? Otherwise I'd prefer to keep this off the issue tracker. You can contact me via the e-mail address in the commit messages and I'll be happy to answer your questions.
